### PR TITLE
Create githubJai.md

### LINKED ISSUE #6: Add Bio for Jai
. Create branch -> created branch githubJai
. Add bio file
. Open pull request
. Give and request feedback
. Merge pull request

### PR DESCRIPTION
**Pull request by jaishu**
This resolves #6 with the merge of this pull request

### CODE REVIEW

**Comment by adsk-runa** [comment]
Hello Jai, what is your favorite sports team?

**Comment by jaishu** [comment]
New England Patriots for football and India for cricket ;)

**Comment by jaishu** [comment]
@adsk-runa  how about yours?

**Comment by adsk-runa** [comment]
@jaishu  Montreal Canadiens for Hockey :) I wish I knew more about cricket

**Comment by jaishu** [comment]
Nice! I used to live north of Boston and travel to Montreal for weekends.

**Pull request merged**
