### PR TITLE
Add bio for GitHub Student

### LINKED ISSUE #4: Add bio for githubstudent
- [x] Create a branch
- [x] Add a bio file for githubstudent
- [x] Open a pull request
- [x] Give & receive feedback
- [x] Merge pull request

### PR DESCRIPTION
**Pull request by githubstudent**
This pull request fixes #4 by creating a new bio file for GitHub Student.

### CODE REVIEW

**Comment by ghost** [comment]
feedback

**Comment by githubstudent** [comment]
@pcontejean what do you think now? is this good to go?

**Comment by ghost** [comment]
yes, good to go

**Comment by githubstudent** [comment]
This is what it looks like now:

screen shot 2016-01-12 at 12 40 25 pm

**Pull request merged**
