### PR TITLE
Add bio for mlmallo

### LINKED ISSUE #7: Add bio for mlmallo
- [x] Create a Branch
- [x] Add a bio file for mlmallo
- [x] Open a pull request
- [x] Get and receive feedback
- [x] Merge pull request

### PR DESCRIPTION
**Pull request by mlmallo**
This pull request resolves #7 by creating new bio file for mlmallo.

### CODE REVIEW

**Comment by adsk-runa** [comment]
What is your favorite sports team?

**Comment by mlmallo** [comment]
@Kristy46549871321 - all set?
@adsk-runa - added comment about weekend.  look ok?

**Comment by Kristy46549871321** [comment]
@mlmallo Looks good! :+1:

**Comment by mlmallo** [comment]
This is what it will look like:

mlmallo
Name: mlmallo
Location: Denver, CO
The weekend was fantastic weekend!

**Pull request merged**
